# Generated by Django 6.1 on 2026-09-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='providerprofile',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='servicearea',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
